---
- name: Create SSH directory for root
  file:
    path: /root/.ssh/
    state: directory
    mode: 0700

- name: Create root SSH key pair for PVE
  user:
    name: root
    generate_ssh_key: yes
    ssh_key_file: /root/.ssh/id_rsa
    ssh_key_type: rsa
    ssh_key_comment: "root@{{ inventory_hostname_short }}"

- name: Fetch root SSH public key
  fetch:
    src: /root/.ssh/id_rsa.pub
    dest: "{{ pve_fetch_directory }}/{{ inventory_hostname }}/root_rsa.pub"
    fail_on_missing: yes
    flat: yes

- name: Authorize all hosts' root SSH public keys
  authorized_key:
    user: root
    key: "{{ lookup('file', pve_fetch_directory + '/' + item + '/root_rsa.pub') }}"
  with_items: "{{ groups[pve_group] }}"

- name: Configure SSH clients for connecting to PVE cluster hosts
  blockinfile:
    dest: /etc/ssh/ssh_config
    create: yes
    marker: "# {mark}: PVE host configuration options (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      Host {{ hostvars[host].pve_cluster_ssh_addrs | join(" ") }}
          IdentityFile /root/.ssh/id_rsa
          Port {{ pve_ssh_port }}
      {% endfor %}

- name: Allow root logins from PVE cluster hosts
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "# {mark}: Allow root logins from PVE hosts (managed by ansible)."
    content: |
      {% for host in groups[pve_group] %}
      Match Address {{ hostvars[host].pve_cluster_ssh_addrs | join(",") }}
      PermitRootLogin prohibit-password
      {% endfor %}
    validate: "/usr/sbin/sshd -t -f %s"
  notify:
    - reload sshd configuration

- name: Fetch SSH public host keys
  fetch:
    src: "/etc/ssh/{{ item }}"
    dest: "{{ pve_fetch_directory }}/{{ inventory_hostname }}/{{ item }}"
    flat: yes
  with_items:
    - ssh_host_rsa_key.pub
    - ssh_host_ed25519_key.pub
    - ssh_host_ecdsa_key.pub

- name: "Check status of known hosts file"
  stat:
    path: "/etc/ssh/ssh_known_hosts"
  register: _pve_known_hosts_file

- name: "Add every host's host keys to global known_hosts for default ssh port"
  known_hosts:
    path: "/etc/ssh/ssh_known_hosts"
    name: "{{ item[0] }}"
    key: "{{ hostvars[item[0]].pve_cluster_ssh_addrs | join(',') }} {{ ' '.join(lookup('file', pve_fetch_directory + '/' + item[0] + '/' + item[1]).split()[:-1]) }}"
  with_nested:
    - "{{ groups[pve_group] }}"
    - ['ssh_host_rsa_key.pub', 'ssh_host_ed25519_key.pub', 'ssh_host_ecdsa_key.pub']
  when:
    - "pve_ssh_port == 22"
    - "not (_pve_known_hosts_file.stat.islnk is defined and _pve_known_hosts_file.stat.islnk) or (inventory_hostname == groups[pve_group][0])"

- name: "Add every host's host keys to global known_hosts for none default ssh port"
  known_hosts:
    path: "/etc/ssh/ssh_known_hosts"
    name: "[{{ item[0] }}]:{{ pve_ssh_port }}"
    key: "[{{ hostvars[item[0]].pve_cluster_ssh_addrs | join(']:'+pve_ssh_port|string+',[') }}]:{{ pve_ssh_port }} {{ ' '.join(lookup('file', pve_fetch_directory + '/' + item[0] + '/' + item[1]).split()[:-1]) }}"
  with_nested:
    - "{{ groups[pve_group] }}"
    - ["ssh_host_rsa_key.pub", "ssh_host_ed25519_key.pub", "ssh_host_ecdsa_key.pub"]
  when:
    - "pve_ssh_port != 22"
    - "not (_pve_known_hosts_file.stat.islnk is defined and _pve_known_hosts_file.stat.islnk) or (inventory_hostname == groups[pve_group][0])"

- name: Add PVE-provided ciphers to SSH client config
  lineinfile:
    line: "Ciphers {{ pve_ssh_ciphers }}"
    regexp: "^Ciphers .*"
    insertbefore: BOF
    create: yes
    dest: /root/.ssh/config
